"""Explicit PostgreSQL opt-in; never use DATABASE_URL for destructive tests."""

import os
from contextlib import contextmanager
from pathlib import Path
from tempfile import TemporaryDirectory
from uuid import uuid4

from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url
from sqlalchemy.pool import NullPool, StaticPool

from backend.database import Base


def postgres_requested() -> bool:
    return bool(os.environ.get("TEST_DATABASE_URL"))


def postgres_test_url():
    raw = os.environ.get("TEST_DATABASE_URL")
    if not raw:
        raise RuntimeError("Set TEST_DATABASE_URL explicitly to run PostgreSQL tests")
    url = make_url(raw)
    if (
        url.drivername != "postgresql+psycopg"
        or url.database != "toneflowers_test"
        or url.host not in {"localhost", "127.0.0.1", "::1"}
        or url.query
    ):
        raise RuntimeError(
            "Tests require postgresql+psycopg on localhost, database toneflowers_test, "
            "without URL query options. DATABASE_URL is never used as a test target."
        )
    return url


@contextmanager
def isolated_database(*, file_backed: bool = False, create_tables: bool = True):
    """Each PostgreSQL test owns one random schema in the dedicated test DB."""
    if postgres_requested():
        url = postgres_test_url()
        schema = "tf_test_" + uuid4().hex
        admin = create_engine(url, poolclass=NullPool)
        engine = None
        created = False
        try:
            with admin.begin() as connection:
                connection.execute(text(f'CREATE SCHEMA "{schema}"'))
            created = True
            engine = create_engine(
                url,
                connect_args={
                    "options": f"-csearch_path={schema} -clock_timeout=10000 -cstatement_timeout=20000",
                },
            )
            if create_tables:
                Base.metadata.create_all(engine)
            yield engine
        finally:
            if engine is not None:
                engine.dispose()
            if created:
                # Only the schema generated by this call is removed. Public
                # tables and all development databases are outside this scope.
                with admin.begin() as connection:
                    connection.execute(text(f'DROP SCHEMA "{schema}" CASCADE'))
            admin.dispose()
    else:
        with TemporaryDirectory(prefix="toneflowers-tests-") as directory:
            engine = create_engine(
                f"sqlite:///{Path(directory) / 'orders.db'}" if file_backed else "sqlite://",
                connect_args={"check_same_thread": False, "timeout": 10},
                **({} if file_backed else {"poolclass": StaticPool}),
            )
            try:
                if create_tables:
                    Base.metadata.create_all(engine)
                yield engine
            finally:
                engine.dispose()
